(() => {
  const normalize=(v='')=>{const s=v.toLowerCase();if(s.startsWith('zh-tw')||s.startsWith('zh-hk')||s.startsWith('zh-hant'))return'zh-TW';if(s.startsWith('zh'))return'zh-CN';return['en','fr','es','ja','ko'].find(x=>s.startsWith(x))||'en';};
  const copy={
    en:{nav:['Overview','Support','Privacy','Terms'],eyebrow:'Designed for Apple platforms',title:'Useful tools.<br><span>Private by design.</span>',lede:'A focused native experience designed to help you work with content on your device while keeping you in control.',cta:'Get support',privacyCta:'Read the Privacy Policy',features:[['01','Native experience','Built for Apple platforms with familiar controls and thoughtful interactions.'],['02','On-device approach','Core content processing is designed to happen locally on your device.'],['03','You stay in control','You choose permissions and confirm important actions.']],principleLabel:'Core principle',principle:'Your content stays under your control.',principleCopy:'Core processing is designed to happen locally on your device. Permissions can be changed at any time in system settings.'},
    fr:{nav:['Présentation','Assistance','Confidentialité','Conditions'],eyebrow:'Conçu pour les plateformes Apple',title:'Des outils utiles.<br><span>La confidentialité dès la conception.</span>',lede:'Une expérience native ciblée pour vous aider à gérer le contenu de votre appareil tout en gardant le contrôle.',cta:'Obtenir de l’aide',privacyCta:'Lire la politique de confidentialité',features:[['01','Expérience native','Conçu pour les plateformes Apple avec des commandes familières et des interactions soignées.'],['02','Traitement sur l’appareil','Le traitement principal du contenu est conçu pour avoir lieu localement sur votre appareil.'],['03','Vous gardez le contrôle','Vous choisissez les autorisations et confirmez les actions importantes.']],principleLabel:'Principe essentiel',principle:'Votre contenu reste sous votre contrôle.',principleCopy:'Le traitement principal est conçu pour avoir lieu localement. Les autorisations peuvent être modifiées dans les réglages système.'},
    es:{nav:['Descripción','Soporte','Privacidad','Términos'],eyebrow:'Diseñado para plataformas Apple',title:'Herramientas útiles.<br><span>Privacidad desde el diseño.</span>',lede:'Una experiencia nativa y enfocada para trabajar con el contenido del dispositivo sin perder el control.',cta:'Obtener soporte',privacyCta:'Leer la Política de privacidad',features:[['01','Experiencia nativa','Creada para plataformas Apple con controles familiares e interacciones cuidadas.'],['02','En el dispositivo','El procesamiento principal está diseñado para realizarse localmente en su dispositivo.'],['03','Usted mantiene el control','Usted elige los permisos y confirma las acciones importantes.']],principleLabel:'Principio fundamental',principle:'Su contenido permanece bajo su control.',principleCopy:'El procesamiento principal está diseñado para realizarse localmente. Los permisos pueden cambiarse en los ajustes del sistema.'},
    ja:{nav:['概要','サポート','プライバシー','利用規約'],eyebrow:'Appleプラットフォーム向けに設計',title:'役立つツール。<br><span>プライバシーを設計の中心に。</span>',lede:'端末上のコンテンツを、自分で管理しながら扱うための集中されたネイティブ体験です。',cta:'サポートを見る',privacyCta:'プライバシーポリシーを読む',features:[['01','ネイティブ体験','Appleプラットフォームに合わせた自然な操作と丁寧なインタラクション。'],['02','端末内アプローチ','主要なコンテンツ処理は端末上で行われるよう設計されています。'],['03','利用者が管理','権限を自分で選び、重要な操作を確認できます。']],principleLabel:'基本原則',principle:'コンテンツは利用者の管理下にあります。',principleCopy:'主要な処理は端末内で行われる設計です。権限はシステム設定でいつでも変更できます。'},
    ko:{nav:['개요','지원','개인정보','약관'],eyebrow:'Apple 플랫폼을 위해 설계',title:'유용한 도구.<br><span>개인정보 보호를 기본으로.</span>',lede:'기기의 콘텐츠를 사용자가 직접 관리하며 다룰 수 있도록 설계된 집중도 높은 네이티브 경험입니다.',cta:'지원 받기',privacyCta:'개인정보 처리방침 보기',features:[['01','네이티브 경험','익숙한 제어와 세심한 상호작용으로 Apple 플랫폼에 맞게 제작되었습니다.'],['02','기기 내 접근 방식','핵심 콘텐츠 처리는 기기에서 로컬로 수행되도록 설계되었습니다.'],['03','사용자가 제어','권한을 직접 선택하고 중요한 작업을 확인합니다.']],principleLabel:'핵심 원칙',principle:'콘텐츠는 사용자의 통제 아래 있습니다.',principleCopy:'핵심 처리는 기기에서 수행되도록 설계되었습니다. 권한은 시스템 설정에서 언제든 변경할 수 있습니다.'},
    'zh-CN':{nav:['概览','支持','隐私','条款'],eyebrow:'为 Apple 平台设计',title:'实用工具。<br><span>隐私源于设计。</span>',lede:'专注的原生体验，帮助你处理设备上的内容，同时始终保有控制权。',cta:'获取支持',privacyCta:'阅读隐私政策',features:[['01','原生体验','针对 Apple 平台打造，采用熟悉的控制方式和经过推敲的交互。'],['02','设备本地优先','核心内容处理设计为在你的设备本地完成。'],['03','由你控制','你可以自主选择权限，并确认重要操作。']],principleLabel:'核心原则',principle:'你的内容始终由你控制。',principleCopy:'核心处理设计为在设备本地完成。权限可以随时在系统设置中修改。'},
    'zh-TW':{nav:['概覽','支援','隱私','條款'],eyebrow:'為 Apple 平台設計',title:'實用工具。<br><span>隱私源於設計。</span>',lede:'專注的原生體驗，協助你處理裝置上的內容，同時始終保有控制權。',cta:'取得支援',privacyCta:'閱讀隱私權政策',features:[['01','原生體驗','針對 Apple 平台打造，採用熟悉的控制方式與細緻的互動。'],['02','裝置本機優先','核心內容處理設計為在你的裝置本機完成。'],['03','由你控制','你可以自主選擇權限，並確認重要操作。']],principleLabel:'核心原則',principle:'你的內容始終由你控制。',principleCopy:'核心處理設計為在裝置本機完成。權限可隨時在系統設定中修改。'}
  };
  const extra={
    en:{experienceLabel:'Made to feel straightforward',experienceTitle:'Less friction between intent and action.',steps:[['Choose what matters','Start with the content and permissions you decide to provide.'],['Review with confidence','Clear information helps you understand an action before confirming it.'],['Stay in control','Change permissions, manage purchases, or contact support whenever needed.']],trustLabel:'Clear from the start',trustTitle:'Privacy, purchases, and help—without surprises.',trust:[['Understand your privacy','The policy explains permissions, processing, and retention in plain language.'],['Manage subscriptions with Apple','Billing, cancellation, and eligible refunds are handled through Apple.'],['Reach a real support channel','Questions and issue reports can be sent directly by email.']],trustCta:'Visit Support'},
    fr:{experienceLabel:'Conçu pour rester simple',experienceTitle:'Moins de friction entre l’intention et l’action.',steps:[['Choisissez l’essentiel','Commencez avec le contenu et les autorisations que vous décidez de fournir.'],['Vérifiez sereinement','Des informations claires expliquent une action avant sa confirmation.'],['Gardez le contrôle','Modifiez les autorisations, gérez les achats ou contactez l’assistance.']],trustLabel:'Clair dès le départ',trustTitle:'Confidentialité, achats et aide, sans surprise.',trust:[['Comprendre la confidentialité','La politique explique simplement les autorisations, le traitement et la conservation.'],['Gérer les abonnements avec Apple','La facturation, l’annulation et les remboursements éligibles passent par Apple.'],['Contacter une véritable assistance','Les questions et problèmes peuvent être envoyés directement par e-mail.']],trustCta:'Accéder à l’assistance'},
    es:{experienceLabel:'Diseñado para ser sencillo',experienceTitle:'Menos fricción entre la intención y la acción.',steps:[['Elija lo importante','Comience con el contenido y los permisos que usted decida proporcionar.'],['Revise con confianza','La información clara permite comprender una acción antes de confirmarla.'],['Mantenga el control','Cambie permisos, gestione compras o contacte con soporte cuando lo necesite.']],trustLabel:'Claridad desde el principio',trustTitle:'Privacidad, compras y ayuda sin sorpresas.',trust:[['Comprenda su privacidad','La política explica permisos, procesamiento y conservación con claridad.'],['Gestione suscripciones con Apple','Apple gestiona la facturación, cancelación y reembolsos elegibles.'],['Contacte con soporte real','Puede enviar preguntas e informes de problemas directamente por correo.']],trustCta:'Visitar Soporte'},
    ja:{experienceLabel:'わかりやすさを大切に',experienceTitle:'意図から操作までを、もっとスムーズに。',steps:[['必要なものを選ぶ','提供するコンテンツと権限は利用者が選択します。'],['安心して確認','確定前に操作内容を理解できる、明確な情報を提供します。'],['管理を続ける','権限変更、購入管理、サポートへの連絡を必要な時に行えます。']],trustLabel:'最初から明確に',trustTitle:'プライバシー、購入、サポートに不意打ちはありません。',trust:[['プライバシーを理解','権限、処理、保持についてわかりやすく説明します。'],['Appleでサブスクリプション管理','請求、解約、対象となる返金はAppleを通じて処理されます。'],['直接問い合わせ','質問や問題報告をメールで直接送信できます。']],trustCta:'サポートを見る'},
    ko:{experienceLabel:'간단하고 명확한 경험',experienceTitle:'의도와 실행 사이의 불편을 줄였습니다.',steps:[['중요한 항목 선택','사용자가 제공하기로 선택한 콘텐츠와 권한으로 시작합니다.'],['안심하고 검토','확정하기 전에 작업을 이해할 수 있도록 명확한 정보를 제공합니다.'],['계속 직접 관리','필요할 때 권한 변경, 구매 관리 또는 지원 문의가 가능합니다.']],trustLabel:'처음부터 투명하게',trustTitle:'개인정보, 구매와 지원에 예상치 못한 부분이 없도록.',trust:[['개인정보 보호 이해','권한, 처리 및 보관 방식을 명확한 언어로 설명합니다.'],['Apple에서 구독 관리','청구, 취소 및 가능한 환불은 Apple을 통해 처리됩니다.'],['직접 지원 문의','질문과 문제 신고를 이메일로 직접 보낼 수 있습니다.']],trustCta:'지원 방문'},
    'zh-CN':{experienceLabel:'简单直接的体验',experienceTitle:'减少从意图到操作之间的阻力。',steps:[['选择重要内容','从你决定提供的内容和权限开始。'],['放心检查','清楚的信息帮助你在确认之前理解操作结果。'],['始终保持控制','随时修改权限、管理购买或联系支持。']],trustLabel:'从一开始就保持透明',trustTitle:'隐私、购买和支持，没有意外。',trust:[['理解隐私方式','隐私政策以清楚的语言说明权限、处理和保留方式。'],['通过 Apple 管理订阅','计费、取消以及符合条件的退款均通过 Apple 处理。'],['直接获得支持','问题和故障报告可以直接通过电子邮件发送。']],trustCta:'访问支持页面'},
    'zh-TW':{experienceLabel:'簡單直接的體驗',experienceTitle:'減少從意圖到操作之間的阻力。',steps:[['選擇重要內容','從你決定提供的內容與權限開始。'],['放心檢查','清楚的資訊協助你在確認之前理解操作結果。'],['始終保持控制','隨時修改權限、管理購買或聯絡支援。']],trustLabel:'從一開始就保持透明',trustTitle:'隱私、購買與支援，沒有意外。',trust:[['理解隱私方式','隱私權政策以清楚的語言說明權限、處理和保留方式。'],['透過 Apple 管理訂閱','計費、取消以及符合條件的退款均透過 Apple 處理。'],['直接取得支援','問題和故障報告可以直接透過電子郵件傳送。']],trustCta:'前往支援頁面'}
  };
  const lang=normalize(localStorage.getItem('language')||'en'),c=copy[lang]||copy.en,x=extra[lang]||extra.en;
  document.documentElement.lang=lang;document.querySelector('[data-app-language]').value=lang;
  document.querySelectorAll('[data-app-nav]').forEach(node=>{const i={overview:0,support:1,privacy:2,terms:3}[node.dataset.appNav];node.textContent=c.nav[i];});
  const set=(q,v)=>{const n=document.querySelector(q);if(n)n.innerHTML=v;};
  set('[data-app-eyebrow]',c.eyebrow);set('[data-app-title]',c.title);set('[data-app-lede]',c.lede);set('[data-app-cta]',c.cta);set('[data-app-privacy]',c.privacyCta);set('[data-app-principle-label]',c.principleLabel);set('[data-app-principle]',c.principle);set('[data-app-principle-copy]',c.principleCopy);
  set('[data-app-features]',c.features.map(([n,h,p])=>`<article><small>${n}</small><h2>${h}</h2><p>${p}</p></article>`).join(''));
  set('[data-app-experience-label]',x.experienceLabel);set('[data-app-experience-title]',x.experienceTitle);set('[data-app-experience]',x.steps.map(([h,p])=>`<li><h3>${h}</h3><p>${p}</p></li>`).join(''));
  set('[data-app-trust-label]',x.trustLabel);set('[data-app-trust-title]',x.trustTitle);set('[data-app-trust]',x.trust.map(([h,p])=>`<article><h3>${h}</h3><p>${p}</p></article>`).join(''));set('[data-app-trust-cta]',x.trustCta);
  document.querySelector('[data-app-language]').addEventListener('change',e=>{localStorage.setItem('language',normalize(e.target.value));location.reload();});
  document.querySelector('[data-theme-toggle]').addEventListener('click',()=>{const n=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=n;localStorage.setItem('theme',n);});
})();
