(() => {
  const normalize=(v='')=>{const s=v.toLowerCase();if(s.startsWith('zh-tw')||s.startsWith('zh-hk')||s.startsWith('zh-hant'))return'zh-TW';if(s.startsWith('zh'))return'zh-CN';return['en','fr','es','ja','ko'].find(x=>s.startsWith(x))||'en';};
  const copy={
    en:{back:'Back to writing',title:'The path from zero to independent developer',intro:'Notes on product ideas, independent development, market judgment, and rapid validation.',date:'March 30, 2025',reading:'6 min read',sections:[['Starting from zero','Independent development is challenging and rewarding. It means taking responsibility for product decisions, design, engineering, and distribution.'],['B2B and B2C','B2B products serve organizations and professional users. They may support higher prices but have longer sales cycles. B2C products can reach users faster, but usually need greater scale.'],['A practical strategy','I focus on two paths: understanding a specific underserved group, and shipping a useful first version early. Real feedback is more valuable than polishing assumptions in isolation.'],['A learning-product idea','One concept is an interactive way for different age groups to understand AI through games, cards, small applications, and practical explanations. The goal is genuine understanding rather than feature quantity.'],['Product values','My approach is pragmatic: interface and technology should solve a real problem. Clear interactions and useful outcomes matter more than visible complexity.'],['Execution','Start with a small native prototype, publish it, observe how people use it, and let evidence guide the next iteration.']]},
    fr:{back:'Retour aux articles',title:'Le chemin vers le développement indépendant',intro:'Notes sur les idées de produits, le développement indépendant, le marché et la validation rapide.',date:'30 mars 2025',reading:'6 min de lecture',sections:[['Partir de zéro','Le développement indépendant est exigeant et enrichissant. Il faut assumer les décisions produit, le design, l’ingénierie et la distribution.'],['B2B et B2C','Le B2B sert les organisations et professionnels, avec des prix souvent plus élevés mais des cycles de vente plus longs. Le B2C touche plus vite le public mais demande généralement davantage d’échelle.'],['Une stratégie pratique','Je privilégie deux voies : comprendre un groupe précis mal servi et publier rapidement une première version utile. Les retours réels valent mieux que des hypothèses longuement perfectionnées.'],['Une idée de produit éducatif','Un concept consiste à aider différents âges à comprendre l’IA par des jeux, des cartes, de petites applications et des explications pratiques.'],['Valeurs produit','Mon approche est pragmatique : l’interface et la technologie doivent résoudre un vrai problème. Les résultats utiles comptent plus que la complexité visible.'],['Exécution','Créer un petit prototype natif, le publier, observer son usage et laisser les preuves guider l’itération suivante.']]},
    es:{back:'Volver a los artículos',title:'El camino hacia el desarrollo independiente',intro:'Notas sobre ideas de producto, desarrollo independiente, mercado y validación rápida.',date:'30 de marzo de 2025',reading:'6 min de lectura',sections:[['Empezar desde cero','El desarrollo independiente es exigente y gratificante. Implica asumir decisiones de producto, diseño, ingeniería y distribución.'],['B2B y B2C','B2B atiende a empresas y profesionales, con precios mayores pero ciclos de venta más largos. B2C llega antes al público, aunque suele necesitar más escala.'],['Una estrategia práctica','Me centro en comprender a un grupo específico desatendido y publicar pronto una primera versión útil. Los comentarios reales valen más que perfeccionar supuestos de forma aislada.'],['Una idea educativa','Un concepto es ayudar a distintas edades a comprender la IA mediante juegos, tarjetas, pequeñas aplicaciones y explicaciones prácticas.'],['Valores de producto','Mi enfoque es pragmático: la interfaz y la tecnología deben resolver un problema real. Los resultados útiles importan más que la complejidad visible.'],['Ejecución','Crear un pequeño prototipo nativo, publicarlo, observar su uso y dejar que la evidencia guíe la siguiente iteración.']]},
    ja:{back:'記事一覧へ戻る',title:'ゼロから始めるインディー開発',intro:'プロダクトのアイデア、インディー開発、市場判断、素早い検証についての記録です。',date:'2025年3月30日',reading:'読了約6分',sections:[['ゼロから始める','インディー開発は難しく、同時に大きな学びがあります。プロダクト判断、デザイン、開発、届け方まで自分で担います。'],['B2BとB2C','B2Bは企業や専門家向けで価格を高く設定しやすい一方、販売期間が長くなります。B2Cは早く利用者へ届きますが、より大きな規模が必要です。'],['実践的な戦略','十分に応えられていない特定の利用者を理解し、役立つ最初の版を早く公開することを重視します。実際の反応は、孤立した仮説より価値があります。'],['学習プロダクトのアイデア','ゲーム、カード、小さなアプリ、実用的な説明を通じ、幅広い年齢層がAIを理解する体験を考えています。'],['プロダクトの価値','考え方は実用主義です。画面と技術は現実の問題を解くためにあり、目立つ複雑さより明快な操作と成果が重要です。'],['実行','小さなネイティブの試作を公開し、使われ方を観察し、事実を次の改善につなげます。']]},
    ko:{back:'글 목록으로',title:'처음부터 시작하는 인디 개발자의 길',intro:'제품 아이디어, 인디 개발, 시장 판단과 빠른 검증에 관한 기록입니다.',date:'2025년 3월 30일',reading:'약 6분',sections:[['처음부터 시작하기','인디 개발은 어렵지만 큰 보람이 있습니다. 제품 결정, 디자인, 엔지니어링과 배포를 함께 책임져야 합니다.'],['B2B와 B2C','B2B는 기업과 전문가를 대상으로 하며 가격은 높을 수 있지만 판매 주기가 깁니다. B2C는 사용자에게 빠르게 도달하지만 더 큰 규모가 필요합니다.'],['실용적인 전략','충분히 지원받지 못한 특정 사용자를 이해하고 유용한 첫 버전을 일찍 출시하는 데 집중합니다. 실제 피드백은 혼자 다듬은 가정보다 가치가 큽니다.'],['학습 제품 아이디어','게임, 카드, 작은 앱과 실용적인 설명을 통해 다양한 연령대가 AI를 이해하도록 돕는 개념입니다.'],['제품 가치','저의 접근은 실용적입니다. 인터페이스와 기술은 실제 문제를 해결해야 하며, 눈에 보이는 복잡성보다 명확한 상호작용과 결과가 중요합니다.'],['실행','작은 네이티브 프로토타입을 출시하고 사용 방식을 관찰한 뒤 근거를 다음 개선에 반영합니다.']]},
    'zh-CN':{back:'返回文章列表',title:'从 0 到 1 的独立开发者之路',intro:'记录产品想法，以及对独立开发、市场判断和快速验证的阶段性思考。',date:'2025 年 3 月 30 日',reading:'约 6 分钟阅读',sections:[['从零开始','独立开发充满挑战，也很有回报。开发者需要同时承担产品决策、设计、工程和发布等不同职责。'],['ToB 与 ToC','ToB 面向企业和专业用户，通常客单价更高，但销售周期较长。ToC 能更快触达用户，但往往需要更大的用户规模。'],['务实的策略','我关注两条路径：理解一个尚未被充分服务的具体群体，以及尽早发布有用的第一版。真实反馈比独自完善假设更有价值。'],['一个学习产品想法','其中一个设想，是让不同年龄的用户通过游戏、卡片、小应用和实用说明理解 AI，重点是真正掌握，而不是堆积功能。'],['产品价值','我的方法偏向实用主义：界面和技术应当解决真实问题。清晰的交互和有效结果，比看起来复杂更重要。'],['执行路径','先制作一个小而完整的原生原型，发布并观察真实使用，再让证据指导下一轮迭代。']]},
    'zh-TW':{back:'返回文章列表',title:'從 0 到 1 的獨立開發者之路',intro:'記錄產品想法，以及對獨立開發、市場判斷和快速驗證的階段性思考。',date:'2025 年 3 月 30 日',reading:'約 6 分鐘閱讀',sections:[['從零開始','獨立開發充滿挑戰，也很有回報。開發者需要同時承擔產品決策、設計、工程與發布等不同職責。'],['ToB 與 ToC','ToB 面向企業與專業使用者，通常客單價更高，但銷售週期較長。ToC 能更快觸及使用者，但往往需要更大的使用者規模。'],['務實的策略','我關注兩條路徑：理解一個尚未被充分服務的具體群體，以及儘早發布有用的第一版。真實回饋比獨自完善假設更有價值。'],['一個學習產品想法','其中一個構想，是讓不同年齡的使用者透過遊戲、卡片、小應用程式和實用說明理解 AI，重點是真正掌握，而不是堆積功能。'],['產品價值','我的方法偏向實用主義：介面和技術應當解決真實問題。清晰的互動和有效結果，比看起來複雜更重要。'],['執行路徑','先製作一個小而完整的原生原型，發布並觀察真實使用，再讓證據指導下一輪迭代。']]}
  };
  const lang=normalize(localStorage.getItem('language')||'en'),c=copy[lang]||copy.en;
  document.documentElement.lang=lang;document.querySelector('[data-article-language]').value=lang;
  const set=(q,v)=>{const n=document.querySelector(q);if(n)n.innerHTML=v;};
  set('[data-article-back]',c.back);set('[data-article-title]',c.title);set('[data-article-intro]',c.intro);set('[data-article-date]',c.date);set('[data-article-reading]',c.reading);
  set('[data-article-content]',c.sections.map(([h,p])=>`<section><h2>${h}</h2><p>${p}</p></section>`).join(''));
  document.title=`${c.title} — Zane Liao`;
  document.querySelector('[data-article-language]').addEventListener('change',e=>{localStorage.setItem('language',normalize(e.target.value));location.reload();});
})();
