(() => {
  const supported = ['en', 'fr', 'es', 'ja', 'ko', 'zh-CN', 'zh-TW'];
  const normalize = (value = '') => {
    const v = value.toLowerCase();
    if (v.startsWith('zh-tw') || v.startsWith('zh-hk') || v.startsWith('zh-hant')) return 'zh-TW';
    if (v.startsWith('zh')) return 'zh-CN';
    return supported.find((code) => code.toLowerCase() === v || v.startsWith(code.toLowerCase())) || 'en';
  };
  const locale = normalize(localStorage.getItem('language') || 'en');
  window.SiteI18n = { supported, normalize, locale };

  const home = {
    en: { navLabel:'Main navigation',navFocus:'Focus',navWriting:'Writing',navAbout:'About',navSupport:'Support',heroEyebrow:'Independent developer · Shanghai',heroTitle:'Turn ideas into',heroTitleOutline:'useful things.',heroLede:'Hi, I’m Zane. I study computer science, design digital products, and document the path from thinking to making.',readNotes:'Read my notes',contactMe:'Contact me',signalTitle:'Think independently. Keep building.',signalCopy:'Computer science, product design, and technical practice.',focusTitle:'Areas of focus',focusIntro:'Solving real problems with thoughtful engineering and clear design.',focusOneTitle:'Native development',focusOneCopy:'Exploring Apple platforms and high-quality native experiences.',focusTwoTitle:'Systems & algorithms',focusTwoCopy:'Understanding fundamentals and turning complex problems into reliable implementations.',focusThreeTitle:'Product thinking',focusThreeCopy:'Testing and iterating from discovery and design through release.',writingTitle:'Recent writing',writingIntro:'Notes on independent development, product judgment, and technical practice.',aboutTitle:'Learn, build, ship, then iterate.',aboutOne:'I’m studying computer science and practicing independent development, turning technical ability into useful outcomes by making things consistently.',aboutTwo:'I currently work mainly with Swift, Rust, C++, and Python while exploring algorithms, product design, and entrepreneurship.',contactTitle:'Have an idea? Let’s talk.',footerHelp:'Help & legal',support:'Support',privacy:'Privacy Policy',terms:'Terms of Service'},
    fr: { navLabel:'Navigation principale',navFocus:'Domaines',navWriting:'Articles',navAbout:'À propos',navSupport:'Assistance',heroEyebrow:'Développeur indépendant · Shanghai',heroTitle:'Transformer les idées en',heroTitleOutline:'créations vraiment utiles.',heroLede:'Bonjour, je suis Zane. J’étudie l’informatique, je conçois des produits numériques et je partage le chemin de la réflexion à la réalisation.',readNotes:'Lire mes articles',contactMe:'Me contacter',signalTitle:'Penser librement. Continuer à créer.',signalCopy:'Informatique, conception de produits et pratique technique.',focusTitle:'Domaines d’intérêt',focusIntro:'Résoudre de vrais problèmes avec une ingénierie rigoureuse et un design clair.',focusOneTitle:'Développement natif',focusOneCopy:'Explorer les plateformes Apple et des expériences natives de qualité.',focusTwoTitle:'Systèmes et algorithmes',focusTwoCopy:'Comprendre les fondements et transformer les problèmes complexes en solutions fiables.',focusThreeTitle:'Pensée produit',focusThreeCopy:'Tester et améliorer, de la découverte au lancement.',writingTitle:'Articles récents',writingIntro:'Notes sur le développement indépendant, le produit et la pratique technique.',aboutTitle:'Apprendre, créer, publier, puis améliorer.',aboutOne:'J’étudie l’informatique et pratique le développement indépendant afin de transformer mes compétences en résultats utiles.',aboutTwo:'Je travaille principalement avec Swift, Rust, C++ et Python, tout en explorant les algorithmes, le design produit et l’entrepreneuriat.',contactTitle:'Une idée ? Parlons-en.',footerHelp:'Aide et mentions légales',support:'Assistance',privacy:'Politique de confidentialité',terms:'Conditions d’utilisation'},
    es: { navLabel:'Navegación principal',navFocus:'Enfoque',navWriting:'Artículos',navAbout:'Acerca de',navSupport:'Soporte',heroEyebrow:'Desarrollador independiente · Shanghái',heroTitle:'Convertir ideas en',heroTitleOutline:'cosas realmente útiles.',heroLede:'Hola, soy Zane. Estudio informática, diseño productos digitales y documento el camino desde la idea hasta la creación.',readNotes:'Leer artículos',contactMe:'Contactarme',signalTitle:'Pensar con independencia. Seguir creando.',signalCopy:'Informática, diseño de producto y práctica técnica.',focusTitle:'Áreas de interés',focusIntro:'Resolver problemas reales con ingeniería sólida y diseño claro.',focusOneTitle:'Desarrollo nativo',focusOneCopy:'Explorando plataformas Apple y experiencias nativas de alta calidad.',focusTwoTitle:'Sistemas y algoritmos',focusTwoCopy:'Comprender los fundamentos y convertir problemas complejos en soluciones fiables.',focusThreeTitle:'Pensamiento de producto',focusThreeCopy:'Probar e iterar desde el descubrimiento y el diseño hasta el lanzamiento.',writingTitle:'Artículos recientes',writingIntro:'Notas sobre desarrollo independiente, criterio de producto y práctica técnica.',aboutTitle:'Aprender, crear, publicar y volver a iterar.',aboutOne:'Estudio informática y practico el desarrollo independiente para convertir habilidades técnicas en resultados útiles.',aboutTwo:'Trabajo principalmente con Swift, Rust, C++ y Python, y también exploro algoritmos, diseño de producto y emprendimiento.',contactTitle:'¿Tienes una idea? Hablemos.',footerHelp:'Ayuda y legal',support:'Soporte',privacy:'Política de privacidad',terms:'Términos de servicio'},
    ja: { navLabel:'メインナビゲーション',navFocus:'分野',navWriting:'記事',navAbout:'プロフィール',navSupport:'サポート',heroEyebrow:'インディー開発者 · 上海',heroTitle:'アイデアを',heroTitleOutline:'本当に役立つ形へ。',heroLede:'Zaneです。コンピュータサイエンスを学び、デジタルプロダクトを設計し、考えるところから形にするまでを記録しています。',readNotes:'記事を読む',contactMe:'お問い合わせ',signalTitle:'自分で考え、作り続ける。',signalCopy:'コンピュータサイエンス、プロダクトデザイン、技術実践。',focusTitle:'注力分野',focusIntro:'堅実なエンジニアリングと明快なデザインで、現実の課題を解決します。',focusOneTitle:'ネイティブ開発',focusOneCopy:'Appleプラットフォームと質の高いネイティブ体験を探究しています。',focusTwoTitle:'システムとアルゴリズム',focusTwoCopy:'基礎を理解し、複雑な問題を信頼できる実装へ変えます。',focusThreeTitle:'プロダクト思考',focusThreeCopy:'発見、設計、公開まで検証と改善を続けます。',writingTitle:'最近の記事',writingIntro:'インディー開発、プロダクト判断、技術実践について。',aboutTitle:'学び、作り、届け、また改善する。',aboutOne:'コンピュータサイエンスとインディー開発を学び、継続的な制作を通じて技術を価値へ変えています。',aboutTwo:'主にSwift、Rust、C++、Pythonを使い、アルゴリズム、プロダクトデザイン、起業も学んでいます。',contactTitle:'アイデアがありますか？話しましょう。',footerHelp:'ヘルプと法的情報',support:'サポート',privacy:'プライバシーポリシー',terms:'利用規約'},
    ko: { navLabel:'주요 탐색',navFocus:'관심 분야',navWriting:'글',navAbout:'소개',navSupport:'지원',heroEyebrow:'인디 개발자 · 상하이',heroTitle:'아이디어를',heroTitleOutline:'실제로 유용한 결과물로.',heroLede:'안녕하세요, Zane입니다. 컴퓨터 과학을 공부하고 디지털 제품을 설계하며 생각에서 구현까지의 과정을 기록합니다.',readNotes:'글 읽기',contactMe:'연락하기',signalTitle:'독립적으로 생각하고 계속 만듭니다.',signalCopy:'컴퓨터 과학, 제품 디자인, 기술 실험.',focusTitle:'관심 분야',focusIntro:'탄탄한 엔지니어링과 명확한 디자인으로 실제 문제를 해결합니다.',focusOneTitle:'네이티브 개발',focusOneCopy:'Apple 플랫폼과 완성도 높은 네이티브 경험을 탐구합니다.',focusTwoTitle:'시스템과 알고리즘',focusTwoCopy:'기본 원리를 이해하고 복잡한 문제를 신뢰할 수 있는 구현으로 바꿉니다.',focusThreeTitle:'제품 사고',focusThreeCopy:'발견과 디자인에서 출시까지 검증하고 개선합니다.',writingTitle:'최근 글',writingIntro:'인디 개발, 제품 판단, 기술 실무에 관한 기록입니다.',aboutTitle:'배우고, 만들고, 출시하고, 다시 개선합니다.',aboutOne:'컴퓨터 과학과 인디 개발을 공부하며 꾸준히 만들어 기술 역량을 실제 가치로 바꾸고 있습니다.',aboutTwo:'주로 Swift, Rust, C++, Python을 사용하며 알고리즘, 제품 디자인, 창업도 탐구합니다.',contactTitle:'아이디어가 있나요? 이야기해요.',footerHelp:'도움말 및 법률',support:'지원',privacy:'개인정보 처리방침',terms:'서비스 약관'},
    'zh-CN': { navLabel:'主要导航',navFocus:'方向',navWriting:'文章',navAbout:'关于',navSupport:'支持',heroEyebrow:'独立开发者 · 上海',heroTitle:'把想法变成',heroTitleOutline:'真正有用的作品。',heroLede:'你好，我是 Zane。我学习计算机科学、设计数字产品，并记录从思考到实现的过程。',readNotes:'阅读文章',contactMe:'联系我',signalTitle:'独立思考，持续构建',signalCopy:'计算机科学、产品设计与技术实践。',focusTitle:'关注方向',focusIntro:'用扎实的工程和清晰的设计解决真实问题。',focusOneTitle:'原生开发',focusOneCopy:'关注 Apple 平台与高质量的原生体验。',focusTwoTitle:'系统与算法',focusTwoCopy:'理解底层原理，并把复杂问题转化为可靠实现。',focusThreeTitle:'产品思维',focusThreeCopy:'从需求、设计到发布，持续验证和迭代。',writingTitle:'最近文章',writingIntro:'关于独立开发、产品判断与技术实践。',aboutTitle:'学习、构建、发布，然后继续迭代。',aboutOne:'我正在学习计算机科学并实践独立开发，希望通过持续做产品，把技术能力转化为真实价值。',aboutTwo:'目前主要使用 Swift、Rust、C++ 和 Python，也持续研究算法、产品设计和创业。',contactTitle:'有想法？一起聊聊。',footerHelp:'帮助与法律',support:'支持',privacy:'隐私政策',terms:'服务条款'},
    'zh-TW': { navLabel:'主要導覽',navFocus:'方向',navWriting:'文章',navAbout:'關於',navSupport:'支援',heroEyebrow:'獨立開發者 · 上海',heroTitle:'把想法變成',heroTitleOutline:'真正有用的作品。',heroLede:'你好，我是 Zane。我學習電腦科學、設計數位產品，並記錄從思考到實現的過程。',readNotes:'閱讀文章',contactMe:'聯絡我',signalTitle:'獨立思考，持續建構',signalCopy:'電腦科學、產品設計與技術實踐。',focusTitle:'關注方向',focusIntro:'用扎實的工程和清晰的設計解決真實問題。',focusOneTitle:'原生開發',focusOneCopy:'關注 Apple 平台與高品質的原生體驗。',focusTwoTitle:'系統與演算法',focusTwoCopy:'理解底層原理，並把複雜問題轉化為可靠實作。',focusThreeTitle:'產品思維',focusThreeCopy:'從需求、設計到發布，持續驗證和迭代。',writingTitle:'最近文章',writingIntro:'關於獨立開發、產品判斷與技術實踐。',aboutTitle:'學習、建構、發布，然後繼續迭代。',aboutOne:'我正在學習電腦科學並實踐獨立開發，希望透過持續做產品，把技術能力轉化為真實價值。',aboutTwo:'目前主要使用 Swift、Rust、C++ 和 Python，也持續研究演算法、產品設計和創業。',contactTitle:'有想法？一起聊聊。',footerHelp:'協助與法律',support:'支援',privacy:'隱私權政策',terms:'服務條款'}
  };

  const article = {
    en:['The path from zero to independent developer','Notes on ideas, products, markets, and independent development.'],
    fr:['Le chemin vers le développement indépendant','Notes sur les idées, les produits, le marché et le développement indépendant.'],
    es:['El camino hacia el desarrollo independiente','Notas sobre ideas, productos, mercado y desarrollo independiente.'],
    ja:['ゼロから始めるインディー開発','アイデア、プロダクト、市場、インディー開発についての記録。'],
    ko:['처음부터 시작하는 인디 개발자의 길','아이디어, 제품, 시장과 인디 개발에 관한 기록입니다.'],
    'zh-CN':['从 0 到 1 的独立开发者之路','记录想法，以及关于产品、市场和独立开发的一些思考。'],
    'zh-TW':['從 0 到 1 的獨立開發者之路','記錄想法，以及關於產品、市場和獨立開發的一些思考。']
  };
  const appLabels = {
    en:'App Information', fr:'Informations sur l’app', es:'Información de la app',
    ja:'アプリ情報', ko:'앱 정보', 'zh-CN':'App 信息', 'zh-TW':'App 資訊'
  };
  const apply = (lang) => {
    const dict = {...(home[lang] || home.en),articleTitle:article[lang][0],articleSummary:article[lang][1],appMarketing:appLabels[lang]};
    document.documentElement.lang = lang;
    document.querySelectorAll('[data-i18n]').forEach((node) => { if (dict[node.dataset.i18n]) node.textContent = dict[node.dataset.i18n]; });
    document.querySelectorAll('[data-i18n-aria]').forEach((node) => { if (dict[node.dataset.i18nAria]) node.setAttribute('aria-label', dict[node.dataset.i18nAria]); });
    document.querySelectorAll('[data-language-select]').forEach((select) => { select.value = lang; });
  };
  apply(locale);
  document.addEventListener('change', (event) => {
    if (!event.target.matches('[data-language-select]')) return;
    const lang = normalize(event.target.value);
    localStorage.setItem('language', lang);
    location.reload();
  });
})();
