(() => {
  const locales = ['en','fr','es','ja','ko','zh-CN','zh-TW'];
  const normalize = (v='') => { const s=v.toLowerCase(); if(s.startsWith('zh-tw')||s.startsWith('zh-hk')||s.startsWith('zh-hant'))return'zh-TW'; if(s.startsWith('zh'))return'zh-CN'; return locales.find(x=>s===x.toLowerCase()||s.startsWith(x.toLowerCase()))||'en'; };
  const common = {
    en:{support:'Support',privacy:'Privacy Policy',terms:'Terms of Service',updated:'Last updated: September 9, 2026',app:'App name',appValue:'Zane Liao Apps',email:'Contact email'},
    fr:{support:'Assistance',privacy:'Politique de confidentialité',terms:'Conditions d’utilisation',updated:'Dernière mise à jour : 9 septembre 2026',app:'Nom de l’application',appValue:'Applications de Zane Liao',email:'E-mail de contact'},
    es:{support:'Soporte',privacy:'Política de privacidad',terms:'Términos de servicio',updated:'Última actualización: 9 de septiembre de 2026',app:'Nombre de la aplicación',appValue:'Aplicaciones de Zane Liao',email:'Correo de contacto'},
    ja:{support:'サポート',privacy:'プライバシーポリシー',terms:'利用規約',updated:'最終更新日：2026年9月9日',app:'アプリ名',appValue:'Zane Liao Apps',email:'連絡先メール'},
    ko:{support:'지원',privacy:'개인정보 처리방침',terms:'서비스 약관',updated:'최종 업데이트: 2026년 9월 9일',app:'앱 이름',appValue:'Zane Liao Apps',email:'문의 이메일'},
    'zh-CN':{support:'支持',privacy:'隐私政策',terms:'服务条款',updated:'最后更新：2026 年 9 月 9 日',app:'App 名称',appValue:'Zane Liao Apps',email:'联系邮箱'},
    'zh-TW':{support:'支援',privacy:'隱私權政策',terms:'服務條款',updated:'最後更新：2026 年 9 月 9 日',app:'App 名稱',appValue:'Zane Liao Apps',email:'聯絡信箱'}
  };
  const pages = {
    en:{
      privacy:{eyebrow:'Legal · Privacy',title:'Privacy Policy',lede:'This policy explains how apps developed by Zane Liao access, process, store, and protect information.',notice:'Core photo, video, and file processing is designed to happen on your device. Personal files are not uploaded to developer-operated servers.',sections:[['1. Information We Collect','The App does not require an account and does not operate a server that stores the contents of your photos, videos, documents, audio, or other personal files. Device information is accessed only when needed for a feature you choose to use.'],['2. Photos, Videos, and Files','If you grant permission, the App may access your photo library or files you select through Apple system pickers. This access is used to display, organize, analyze, convert, or delete items only when requested by you. You can change permissions in Settings.'],['3. Local Processing and Deletion','Supported processing is performed locally unless the App explicitly says otherwise. Deletion occurs only after an action you initiate or confirm. Some deleted media may remain in Apple’s Recently Deleted area.'],['4. Purchases and Subscriptions','Apple processes App Store purchases and subscriptions. The developer does not receive your full payment-card or bank information. The App may receive purchase status needed to unlock features.'],['5. Analytics, Advertising, and Third Parties','The App does not sell personal information, use personal files for advertising, or use third-party advertising SDKs to track you. Apple system services are governed by Apple’s policies. This policy will be updated if other data-processing services are added.'],['6. Retention, Security, and Children','Local settings and authorized-file references may remain until removed, reset, or the App is uninstalled. No system can be guaranteed completely secure. The App is not directed to children and does not knowingly collect children’s personal information on developer servers.'],['7. Changes and Contact','We may update this policy when features or legal requirements change. For privacy questions or requests, contact <a href="mailto:lzq666amn@gmail.com">lzq666amn@gmail.com</a>.']]},
      terms:{eyebrow:'Legal · Terms',title:'Terms of Service',lede:'These terms govern your use of apps developed by Zane Liao.',notice:'By downloading, installing, purchasing, or using the App, you agree to these terms. If you do not agree, do not use the App.',sections:[['1. Use of the App','You receive a limited, personal, non-exclusive, non-transferable, and revocable license to use the App on devices you own or control, subject to applicable Apple terms and law.'],['2. Your Content and Actions','Your files remain yours. Review items before any deletion or irreversible action and keep appropriate backups. Automated classifications or recommendations may be incomplete or inaccurate.'],['3. Permissions and Local Processing','Some features require access to device resources you select. You may revoke permission in Settings, which may prevent those features from working. Processing is designed to occur locally as described in the Privacy Policy.'],['4. Purchases and Subscriptions','Apple processes purchases. Auto-renewable subscriptions renew unless canceled before the next renewal. Manage or cancel them through your Apple Account; deleting the App does not cancel a subscription. Trials may convert to paid subscriptions under the terms shown before purchase.'],['5. Refunds','Apple administers App Store payments and refunds. Refund eligibility and processing are subject to Apple’s policies and applicable law.'],['6. Acceptable Use and Intellectual Property','Do not use the App unlawfully, interfere with security, violate others’ rights, or redistribute the App without permission. The App’s software, design, and branding remain the developer’s intellectual property.'],['7. Availability, Warranty, and Liability','Features may change or be discontinued. To the extent permitted by law, the App is provided “as is” without guarantees of uninterrupted or error-free operation. Liability is limited only where applicable law allows; mandatory consumer rights remain unaffected.'],['8. Changes and Contact','These terms may be updated as the App or legal requirements change. Questions may be sent to <a href="mailto:lzq666amn@gmail.com">lzq666amn@gmail.com</a>.']]},
      support:{eyebrow:'Help · Support',title:'App Support',lede:'Find answers, report an issue, or get help with an app developed by Zane Liao.',notice:'When contacting support, include the exact app name shown on your device or App Store receipt.',sections:[['Frequently Asked Questions','<strong>How do I restore a purchase?</strong><br>Open the App’s purchase screen and use Restore Purchases when available. Make sure you are signed in with the Apple Account used for the purchase.<br><br><strong>Why can’t the App access my photos or files?</strong><br>Review the App’s permissions in iOS Settings. Some features require access to content you explicitly select.<br><br><strong>How do I cancel a subscription?</strong><br>Open Settings, tap your name, then Subscriptions, select the App, and choose Cancel Subscription.'],['How to Report a Problem','Email <a href="mailto:lzq666amn@gmail.com">lzq666amn@gmail.com</a> with the app name, device model, iOS version, a description of what happened, steps to reproduce it, and screenshots if they do not contain sensitive information. Do not send personal files, passwords, payment-card details, or other confidential data.'],['Privacy','Read the <a href="../privacy/">Privacy Policy</a> to understand device permissions, local processing, data retention, and contact options.'],['Subscriptions and Refunds','Subscriptions are billed and managed by Apple. Deleting an app does not cancel a subscription. You can manage subscriptions in your Apple Account settings. Refund requests for App Store purchases are reviewed and processed by Apple under its policies.'],['Response Time','Support messages are reviewed as soon as reasonably possible. Complex technical issues may require additional information or an app update.']]}
    },
    fr:{
      privacy:{eyebrow:'Mentions légales · Confidentialité',title:'Politique de confidentialité',lede:'Cette politique explique comment les applications développées par Zane Liao accèdent aux informations, les traitent, les conservent et les protègent.',notice:'Le traitement principal des photos, vidéos et fichiers est conçu pour avoir lieu sur votre appareil. Les fichiers personnels ne sont pas envoyés aux serveurs du développeur.',sections:[['1. Informations collectées','L’App ne nécessite pas de compte et n’exploite aucun serveur stockant le contenu de vos fichiers personnels. Les informations de l’appareil ne sont consultées que pour une fonction que vous choisissez.'],['2. Photos, vidéos et fichiers','Avec votre autorisation, l’App peut accéder à la photothèque ou aux fichiers sélectionnés via les outils Apple afin de les afficher, organiser, analyser, convertir ou supprimer à votre demande. Les autorisations sont modifiables dans Réglages.'],['3. Traitement local et suppression','Le traitement pris en charge est effectué localement, sauf indication contraire explicite. Une suppression intervient uniquement après votre action ou confirmation. Certains médias peuvent rester dans « Supprimés récemment ».'],['4. Achats et abonnements','Apple traite les achats et abonnements App Store. Le développeur ne reçoit pas vos données bancaires complètes. L’App peut recevoir l’état d’achat nécessaire à l’activation de fonctions.'],['5. Analyses, publicité et tiers','L’App ne vend pas de données personnelles, n’utilise pas vos fichiers pour la publicité et ne vous suit pas avec des SDK publicitaires. Les services Apple suivent les politiques d’Apple.'],['6. Conservation, sécurité et enfants','Les réglages locaux peuvent rester jusqu’à leur suppression, réinitialisation ou désinstallation. Aucun système n’est totalement sécurisé. L’App ne vise pas les enfants et ne collecte pas sciemment leurs données sur des serveurs du développeur.'],['7. Modifications et contact','Cette politique peut évoluer. Pour toute question : <a href="mailto:lzq666amn@gmail.com">lzq666amn@gmail.com</a>.']]},
      terms:{eyebrow:'Mentions légales · Conditions',title:'Conditions d’utilisation',lede:'Ces conditions régissent l’utilisation des applications développées par Zane Liao.',notice:'En téléchargeant, installant, achetant ou utilisant l’App, vous acceptez ces conditions.',sections:[['1. Utilisation','Vous recevez une licence limitée, personnelle, non exclusive, non transférable et révocable, sous réserve des conditions Apple et de la loi.'],['2. Vos contenus et actions','Vos fichiers restent les vôtres. Vérifiez-les avant toute suppression et conservez des sauvegardes. Les recommandations automatisées peuvent être incomplètes.'],['3. Autorisations et traitement local','Certaines fonctions nécessitent les accès que vous accordez. Vous pouvez les retirer dans Réglages. Le traitement local est décrit dans la Politique de confidentialité.'],['4. Achats et abonnements','Apple traite les achats. Les abonnements se renouvellent sauf annulation avant l’échéance. Gérez-les via votre compte Apple ; supprimer l’App ne les annule pas.'],['5. Remboursements','Apple administre paiements et remboursements selon ses politiques et la loi applicable.'],['6. Usage acceptable et propriété','N’utilisez pas l’App illégalement, ne contournez pas sa sécurité et ne portez pas atteinte aux droits d’autrui. Le logiciel, le design et la marque restent la propriété du développeur.'],['7. Disponibilité et responsabilité','Les fonctions peuvent évoluer. Dans les limites légales, l’App est fournie « en l’état ». Les droits impératifs des consommateurs restent applicables.'],['8. Modifications et contact','Ces conditions peuvent être mises à jour. Contact : <a href="mailto:lzq666amn@gmail.com">lzq666amn@gmail.com</a>.']]},
      support:{eyebrow:'Aide · Assistance',title:'Assistance des applications',lede:'Trouvez des réponses ou signalez un problème concernant une application développée par Zane Liao.',notice:'Indiquez le nom exact de l’application affiché sur votre appareil ou votre reçu App Store.',sections:[['Questions fréquentes','<strong>Restaurer un achat :</strong> utilisez « Restaurer les achats » dans l’App avec le compte Apple de l’achat.<br><br><strong>Accès aux photos ou fichiers :</strong> vérifiez les autorisations de l’App dans Réglages.<br><br><strong>Annuler un abonnement :</strong> ouvrez Réglages, votre nom, Abonnements, puis sélectionnez l’App.'],['Signaler un problème','Écrivez à <a href="mailto:lzq666amn@gmail.com">lzq666amn@gmail.com</a> avec le nom de l’App, le modèle, la version iOS, les étapes et des captures sans données sensibles. N’envoyez ni mots de passe ni données bancaires.'],['Confidentialité','Consultez la <a href="../privacy/">Politique de confidentialité</a>.'],['Abonnements et remboursements','Apple facture et gère les abonnements. La suppression de l’App ne les annule pas. Apple examine les demandes de remboursement selon ses politiques.'],['Délai de réponse','Les demandes sont examinées dès que raisonnablement possible. Un problème complexe peut nécessiter des informations supplémentaires ou une mise à jour.']]}
    },
    es:{
      privacy:{eyebrow:'Legal · Privacidad',title:'Política de privacidad',lede:'Esta política explica cómo las aplicaciones desarrolladas por Zane Liao acceden, procesan, almacenan y protegen la información.',notice:'El procesamiento principal de fotos, vídeos y archivos está diseñado para realizarse en el dispositivo. Los archivos personales no se suben a servidores del desarrollador.',sections:[['1. Información recopilada','La App no requiere una cuenta ni opera un servidor que almacene el contenido de sus archivos personales. Solo accede a información del dispositivo para funciones que usted decide utilizar.'],['2. Fotos, vídeos y archivos','Con permiso, la App puede acceder a la fototeca o a archivos seleccionados mediante controles de Apple para mostrarlos, organizarlos, analizarlos, convertirlos o eliminarlos cuando usted lo solicite. Puede cambiar los permisos en Ajustes.'],['3. Procesamiento local y eliminación','El procesamiento compatible se realiza localmente salvo indicación expresa. La eliminación requiere una acción o confirmación suya. Algunos elementos pueden permanecer en “Eliminado recientemente”.'],['4. Compras y suscripciones','Apple procesa las compras y suscripciones. El desarrollador no recibe sus datos bancarios completos. La App puede recibir el estado de compra necesario para habilitar funciones.'],['5. Analítica, publicidad y terceros','La App no vende datos personales, no usa archivos para publicidad ni utiliza SDK publicitarios para rastrearle. Los servicios de Apple se rigen por sus políticas.'],['6. Conservación, seguridad y menores','Los ajustes locales pueden permanecer hasta su eliminación, restablecimiento o desinstalación. Ningún sistema es totalmente seguro. La App no se dirige a menores ni recopila conscientemente sus datos en servidores del desarrollador.'],['7. Cambios y contacto','Podemos actualizar esta política. Contacto: <a href="mailto:lzq666amn@gmail.com">lzq666amn@gmail.com</a>.']]},
      terms:{eyebrow:'Legal · Términos',title:'Términos de servicio',lede:'Estos términos regulan el uso de las aplicaciones desarrolladas por Zane Liao.',notice:'Al descargar, instalar, comprar o usar la App, acepta estos términos.',sections:[['1. Uso de la App','Recibe una licencia limitada, personal, no exclusiva, intransferible y revocable, sujeta a las condiciones de Apple y a la ley.'],['2. Su contenido y acciones','Sus archivos siguen siendo suyos. Revise los elementos antes de eliminarlos y mantenga copias de seguridad. Las recomendaciones automáticas pueden ser incompletas.'],['3. Permisos y procesamiento local','Algunas funciones requieren permisos que usted concede. Puede revocarlos en Ajustes. El procesamiento local se describe en la Política de privacidad.'],['4. Compras y suscripciones','Apple procesa las compras. Las suscripciones se renuevan salvo cancelación previa. Adminístrelas desde su cuenta Apple; eliminar la App no cancela una suscripción.'],['5. Reembolsos','Apple administra pagos y reembolsos conforme a sus políticas y la legislación aplicable.'],['6. Uso aceptable y propiedad','No use la App ilegalmente, no interfiera con su seguridad ni vulnere derechos ajenos. El software, diseño y marca pertenecen al desarrollador.'],['7. Disponibilidad y responsabilidad','Las funciones pueden cambiar. En la medida permitida, la App se ofrece “tal cual”. Los derechos obligatorios del consumidor no se ven afectados.'],['8. Cambios y contacto','Estos términos pueden actualizarse. Contacto: <a href="mailto:lzq666amn@gmail.com">lzq666amn@gmail.com</a>.']]},
      support:{eyebrow:'Ayuda · Soporte',title:'Soporte de aplicaciones',lede:'Encuentre respuestas o informe de un problema con una aplicación desarrollada por Zane Liao.',notice:'Incluya el nombre exacto de la aplicación que aparece en su dispositivo o recibo del App Store.',sections:[['Preguntas frecuentes','<strong>Restaurar compras:</strong> use Restaurar compras dentro de la App con la cuenta Apple original.<br><br><strong>Acceso a fotos o archivos:</strong> revise los permisos de la App en Ajustes.<br><br><strong>Cancelar una suscripción:</strong> vaya a Ajustes, su nombre, Suscripciones y seleccione la App.'],['Cómo informar de un problema','Escriba a <a href="mailto:lzq666amn@gmail.com">lzq666amn@gmail.com</a> indicando la App, modelo, versión de iOS, pasos y capturas sin datos sensibles. No envíe contraseñas ni datos bancarios.'],['Privacidad','Consulte la <a href="../privacy/">Política de privacidad</a>.'],['Suscripciones y reembolsos','Apple factura y administra las suscripciones. Eliminar la App no las cancela. Apple evalúa las solicitudes de reembolso según sus políticas.'],['Tiempo de respuesta','Los mensajes se revisan tan pronto como sea razonablemente posible. Los problemas complejos pueden requerir más información o una actualización.']]}
    },
    ja:{
      privacy:{eyebrow:'法的情報 · プライバシー',title:'プライバシーポリシー',lede:'本ポリシーは、Zane Liaoが開発するアプリにおける情報のアクセス、処理、保存、保護について説明します。',notice:'写真、動画、ファイルの主要な処理は端末上で行われる設計です。個人ファイルを開発者のサーバーへアップロードしません。',sections:[['1. 収集する情報','本アプリはアカウントを必要とせず、個人ファイルの内容を保存する開発者サーバーを運用しません。端末情報には、利用者が選んだ機能に必要な場合のみアクセスします。'],['2. 写真、動画、ファイル','許可した場合、表示、整理、分析、変換、削除のため、Appleの選択画面を通じて写真や選択ファイルへアクセスすることがあります。権限は「設定」で変更できます。'],['3. 端末内処理と削除','明示しない限り、対応する処理は端末内で行われます。削除は利用者の操作または確認後にのみ実行され、一部は「最近削除した項目」に残る場合があります。'],['4. 購入とサブスクリプション','App Storeの購入はAppleが処理します。開発者は完全なカード・銀行情報を受け取りません。機能解放に必要な購入状態を受け取る場合があります。'],['5. 分析、広告、第三者','個人情報の販売、個人ファイルの広告利用、広告SDKによる追跡は行いません。AppleのサービスにはAppleの方針が適用されます。'],['6. 保持、安全性、子ども','ローカル設定は削除、リセット、アンインストールまで残る場合があります。完全な安全性は保証できません。本アプリは子ども向けではなく、開発者サーバーで子どもの情報を故意に収集しません。'],['7. 変更と連絡先','本ポリシーは更新される場合があります。お問い合わせ：<a href="mailto:lzq666amn@gmail.com">lzq666amn@gmail.com</a>']]},
      terms:{eyebrow:'法的情報 · 規約',title:'利用規約',lede:'本規約は、Zane Liaoが開発するアプリの利用に適用されます。',notice:'ダウンロード、インストール、購入または利用により、本規約に同意したものとみなされます。',sections:[['1. アプリの利用','Appleの規約と法令に従い、所有または管理する端末で利用するための限定的、個人的、非独占的、譲渡不可、取消可能なライセンスを付与します。'],['2. コンテンツと操作','ファイルの所有権は利用者にあります。削除前に内容を確認し、重要なデータはバックアップしてください。自動判定は完全または正確でない場合があります。'],['3. 権限と端末内処理','一部機能は許可が必要です。「設定」で取り消せますが、機能が動作しなくなる場合があります。端末内処理はプライバシーポリシーに記載します。'],['4. 購入とサブスクリプション','購入はAppleが処理します。自動更新は次回更新前に解約しない限り継続します。Apple Accountで管理してください。アプリの削除だけでは解約されません。'],['5. 返金','支払いと返金はAppleが、その方針および適用法に従って管理します。'],['6. 禁止事項と知的財産','違法利用、セキュリティ妨害、権利侵害、無断再配布は禁止です。ソフトウェア、デザイン、ブランドの権利は開発者に帰属します。'],['7. 提供、保証、責任','機能は変更・終了する場合があります。法令で認められる範囲で現状有姿で提供します。強行法規上の消費者権利は制限されません。'],['8. 変更と連絡先','本規約は更新される場合があります。お問い合わせ：<a href="mailto:lzq666amn@gmail.com">lzq666amn@gmail.com</a>']]},
      support:{eyebrow:'ヘルプ · サポート',title:'アプリサポート',lede:'Zane Liaoが開発するアプリについて、回答の確認や問題の報告ができます。',notice:'お問い合わせには、端末またはApp Storeのレシートに表示される正確なアプリ名を記載してください。',sections:[['よくある質問','<strong>購入の復元：</strong>購入時のApple Accountでサインインし、アプリ内の「購入を復元」を使用してください。<br><br><strong>写真やファイルにアクセスできない：</strong>iOSの「設定」で権限を確認してください。<br><br><strong>解約：</strong>「設定」→名前→「サブスクリプション」から対象アプリを選択します。'],['問題を報告する方法','<a href="mailto:lzq666amn@gmail.com">lzq666amn@gmail.com</a>へ、アプリ名、端末、iOS、再現手順、機密情報を含まない画像を送ってください。パスワードやカード情報は送信しないでください。'],['プライバシー','<a href="../privacy/">プライバシーポリシー</a>をご確認ください。'],['サブスクリプションと返金','請求と管理はAppleが行います。アプリを削除しても解約されません。返金申請はAppleが方針に従って審査します。'],['返信について','可能な限り早く確認します。複雑な問題では追加情報やアップデートが必要な場合があります。']]}
    },
    ko:{
      privacy:{eyebrow:'법률 · 개인정보',title:'개인정보 처리방침',lede:'이 방침은 Zane Liao가 개발한 앱이 정보를 접근, 처리, 저장 및 보호하는 방법을 설명합니다.',notice:'사진, 동영상 및 파일의 핵심 처리는 기기에서 수행되도록 설계되었습니다. 개인 파일은 개발자 서버에 업로드되지 않습니다.',sections:[['1. 수집하는 정보','앱은 계정을 요구하지 않으며 개인 파일 내용을 보관하는 개발자 서버를 운영하지 않습니다. 선택한 기능에 필요한 경우에만 기기 정보에 접근합니다.'],['2. 사진, 동영상 및 파일','권한을 부여하면 Apple 시스템 선택기를 통해 사진이나 선택한 파일에 접근하여 요청에 따라 표시, 정리, 분석, 변환 또는 삭제할 수 있습니다. 권한은 설정에서 변경할 수 있습니다.'],['3. 로컬 처리 및 삭제','명시하지 않는 한 지원되는 처리는 기기에서 수행됩니다. 삭제는 사용자가 시작하거나 확인한 후에만 실행되며 일부 항목은 ‘최근 삭제된 항목’에 남을 수 있습니다.'],['4. 구매 및 구독','App Store 구매와 구독은 Apple이 처리합니다. 개발자는 전체 결제 정보를 받지 않습니다. 기능 활성화에 필요한 구매 상태를 받을 수 있습니다.'],['5. 분석, 광고 및 제3자','개인정보를 판매하거나 개인 파일을 광고에 사용하거나 광고 SDK로 추적하지 않습니다. Apple 서비스에는 Apple의 정책이 적용됩니다.'],['6. 보관, 보안 및 아동','로컬 설정은 삭제, 초기화 또는 앱 제거 전까지 남을 수 있습니다. 완전한 보안은 보장할 수 없습니다. 앱은 아동을 대상으로 하지 않으며 개발자 서버에서 아동 정보를 고의로 수집하지 않습니다.'],['7. 변경 및 문의','이 방침은 변경될 수 있습니다. 문의: <a href="mailto:lzq666amn@gmail.com">lzq666amn@gmail.com</a>']]},
      terms:{eyebrow:'법률 · 약관',title:'서비스 약관',lede:'이 약관은 Zane Liao가 개발한 앱의 사용에 적용됩니다.',notice:'앱을 다운로드, 설치, 구매 또는 사용하면 이 약관에 동의하는 것입니다.',sections:[['1. 앱 사용','Apple 약관과 법률에 따라 소유하거나 관리하는 기기에서 사용할 수 있는 제한적이고 개인적이며 비독점적이고 양도 불가능하며 철회 가능한 라이선스를 제공합니다.'],['2. 콘텐츠와 작업','파일은 사용자 소유입니다. 삭제 전 확인하고 중요한 데이터는 백업하십시오. 자동 분류나 권장 사항은 불완전할 수 있습니다.'],['3. 권한 및 로컬 처리','일부 기능에는 사용자가 부여하는 권한이 필요합니다. 설정에서 철회할 수 있으며 해당 기능이 중단될 수 있습니다. 로컬 처리는 개인정보 처리방침에 설명합니다.'],['4. 구매 및 구독','구매는 Apple이 처리합니다. 자동 갱신 구독은 다음 갱신 전에 취소하지 않으면 갱신됩니다. Apple Account에서 관리하십시오. 앱 삭제만으로는 취소되지 않습니다.'],['5. 환불','결제와 환불은 Apple이 정책과 관련 법률에 따라 관리합니다.'],['6. 허용되는 사용 및 지식재산','불법 사용, 보안 방해, 타인의 권리 침해, 무단 재배포를 금지합니다. 소프트웨어, 디자인 및 브랜드는 개발자의 지식재산입니다.'],['7. 가용성, 보증 및 책임','기능은 변경되거나 종료될 수 있습니다. 법이 허용하는 범위에서 앱은 “있는 그대로” 제공됩니다. 강행 소비자 권리는 제한되지 않습니다.'],['8. 변경 및 문의','약관은 변경될 수 있습니다. 문의: <a href="mailto:lzq666amn@gmail.com">lzq666amn@gmail.com</a>']]},
      support:{eyebrow:'도움말 · 지원',title:'앱 지원',lede:'Zane Liao가 개발한 앱에 대한 답변을 찾거나 문제를 신고하세요.',notice:'문의할 때 기기 또는 App Store 영수증에 표시된 정확한 앱 이름을 포함해 주세요.',sections:[['자주 묻는 질문','<strong>구매 복원:</strong> 구매한 Apple Account로 로그인하고 앱의 구매 복원을 사용하세요.<br><br><strong>사진 또는 파일 접근:</strong> iOS 설정에서 앱 권한을 확인하세요.<br><br><strong>구독 취소:</strong> 설정 → 이름 → 구독에서 앱을 선택하세요.'],['문제 신고 방법','<a href="mailto:lzq666amn@gmail.com">lzq666amn@gmail.com</a>으로 앱 이름, 기기 모델, iOS 버전, 재현 단계와 민감정보가 없는 화면을 보내세요. 비밀번호나 결제 정보는 보내지 마세요.'],['개인정보','<a href="../privacy/">개인정보 처리방침</a>을 확인하세요.'],['구독 및 환불','구독 청구와 관리는 Apple이 담당합니다. 앱 삭제만으로 구독이 취소되지 않습니다. 환불 요청은 Apple이 정책에 따라 처리합니다.'],['응답 시간','가능한 한 신속히 확인합니다. 복잡한 문제는 추가 정보나 앱 업데이트가 필요할 수 있습니다.']]}
    },
    'zh-CN':{
      privacy:{eyebrow:'法律 · 隐私',title:'隐私政策',lede:'本政策说明 Zane Liao 开发的应用如何访问、处理、存储和保护信息。',notice:'照片、视频和文件的核心处理设计为在你的设备本地完成。个人文件不会上传到开发者运营的服务器。',sections:[['1. 我们收集的信息','本应用不要求创建账户，也不运营用于存储照片、视频、文档、音频或其他个人文件内容的服务器。只有在你选择使用相关功能时，应用才会访问必要的设备信息。'],['2. 照片、视频和文件','在获得许可后，本应用可通过 Apple 系统选择器访问照片图库或你选择的文件，用于按你的要求显示、整理、分析、转换或删除内容。你可以随时在系统设置中更改权限。'],['3. 本地处理和删除','除非应用内另有明确说明，支持的处理均在设备本地完成。删除仅在你主动发起或确认后执行；部分媒体可能暂时保留在系统“最近删除”中。'],['4. 购买和订阅','App Store 购买与订阅由 Apple 处理。开发者不会收到完整银行卡或银行信息。应用可能接收用于解锁功能的购买状态。'],['5. 分析、广告和第三方','本应用不出售个人信息、不将个人文件用于广告，也不使用第三方广告 SDK 跨应用追踪用户。Apple 系统服务遵循 Apple 的政策；若增加其他数据处理服务，本政策将相应更新。'],['6. 保留、安全和儿童','本地设置及授权文件引用可能保留至被删除、重置或卸载。任何系统都无法保证绝对安全。本应用不专门面向儿童，也不会通过开发者服务器故意收集儿童个人信息。'],['7. 变更与联系','功能或法律要求变化时，我们可能更新本政策。隐私问题或请求请联系 <a href="mailto:lzq666amn@gmail.com">lzq666amn@gmail.com</a>。']]},
      terms:{eyebrow:'法律 · 条款',title:'服务条款',lede:'本条款适用于你使用 Zane Liao 开发的应用。',notice:'下载、安装、购买或使用本应用，即表示你同意这些条款；若不同意，请勿使用。',sections:[['1. 应用使用许可','在遵守 Apple 条款和适用法律的前提下，你获得在自己拥有或控制的设备上使用本应用的有限、个人、非独占、不可转让且可撤销许可。'],['2. 你的内容和操作','你的文件始终归你所有。进行删除或不可逆操作前请仔细检查，并为重要数据保留备份。自动分类或建议可能不完整或不准确。'],['3. 权限和本地处理','部分功能需要你授予设备资源访问权限。你可以在设置中撤销权限，但相关功能可能无法使用。本地处理方式详见隐私政策。'],['4. 购买和订阅','购买由 Apple 处理。自动续订订阅会持续续订，除非在下一次续订前取消。请通过 Apple Account 管理；卸载应用不会自动取消订阅。试用可能按购买前显示的条件转为付费订阅。'],['5. 退款','App Store 付款和退款由 Apple 管理，资格和流程受 Apple 政策及适用法律约束。'],['6. 可接受使用与知识产权','不得违法使用、干扰安全机制、侵犯他人权利或擅自分发应用。应用的软件、设计和品牌属于开发者的知识产权。'],['7. 可用性、保证与责任','功能可能变更或停止。在法律允许范围内，本应用按“现状”提供，不保证无中断或无错误。强制适用的消费者权利不受影响。'],['8. 变更与联系','应用或法律要求变化时，本条款可能更新。问题请发送至 <a href="mailto:lzq666amn@gmail.com">lzq666amn@gmail.com</a>。']]},
      support:{eyebrow:'帮助 · 支持',title:'App 支持',lede:'查找常见问题答案，或报告由 Zane Liao 开发的应用问题。',notice:'联系支持时，请写明设备或 App Store 收据上显示的准确 App 名称。',sections:[['常见问题','<strong>如何恢复购买？</strong><br>使用购买时的 Apple Account 登录，在应用购买页面使用“恢复购买”（若提供）。<br><br><strong>为什么无法访问照片或文件？</strong><br>请在 iOS 设置中检查应用权限，部分功能需要访问你主动选择的内容。<br><br><strong>如何取消订阅？</strong><br>打开“设置”，轻点你的姓名，选择“订阅”，找到对应应用并取消。'],['如何报告问题','发送邮件至 <a href="mailto:lzq666amn@gmail.com">lzq666amn@gmail.com</a>，注明 App 名称、设备型号、iOS 版本、问题描述、复现步骤，以及不含敏感信息的截图。请勿发送个人文件、密码或银行卡信息。'],['隐私政策','请阅读<a href="../privacy/">隐私政策</a>，了解设备权限、本地处理、数据保留和联系渠道。'],['订阅和退款','订阅由 Apple 计费和管理。卸载应用不会取消订阅，你可以在 Apple Account 设置中管理订阅。App Store 购买的退款请求由 Apple 根据其政策审核和处理。'],['响应时间','我们会在合理可行的情况下尽快查看支持邮件。复杂技术问题可能需要补充信息或等待应用更新。']]}
    },
    'zh-TW':{
      privacy:{eyebrow:'法律 · 隱私',title:'隱私權政策',lede:'本政策說明 Zane Liao 開發的應用程式如何存取、處理、儲存及保護資訊。',notice:'照片、影片與檔案的核心處理設計為在你的裝置本機完成。個人檔案不會上傳至開發者營運的伺服器。',sections:[['1. 我們收集的資訊','本應用程式不要求建立帳號，也不營運用於儲存個人檔案內容的伺服器。只有在你選擇使用相關功能時，才會存取必要的裝置資訊。'],['2. 照片、影片與檔案','取得許可後，本應用程式可透過 Apple 系統選擇器存取照片圖庫或你選擇的檔案，用於依你的要求顯示、整理、分析、轉換或刪除。你可在系統設定中變更權限。'],['3. 本機處理與刪除','除非應用程式內另有明確說明，支援的處理皆在裝置本機完成。刪除僅在你主動發起或確認後執行；部分媒體可能暫留於「最近刪除」。'],['4. 購買與訂閱','App Store 購買與訂閱由 Apple 處理。開發者不會收到完整付款資訊。應用程式可能接收用於解鎖功能的購買狀態。'],['5. 分析、廣告與第三方','本應用程式不出售個人資訊、不將個人檔案用於廣告，也不使用廣告 SDK 跨 App 追蹤。Apple 系統服務遵循 Apple 政策。'],['6. 保留、安全與兒童','本機設定可能保留至刪除、重設或解除安裝。任何系統皆無法保證絕對安全。本應用程式並非專為兒童設計，也不會透過開發者伺服器故意收集兒童資訊。'],['7. 變更與聯絡','我們可能更新本政策。隱私問題請聯絡 <a href="mailto:lzq666amn@gmail.com">lzq666amn@gmail.com</a>。']]},
      terms:{eyebrow:'法律 · 條款',title:'服務條款',lede:'本條款適用於你使用 Zane Liao 開發的應用程式。',notice:'下載、安裝、購買或使用本應用程式，即表示你同意本條款。',sections:[['1. 使用許可','在遵守 Apple 條款及法律的前提下，你取得在自己擁有或控制的裝置上使用本應用程式的有限、個人、非專屬、不可轉讓且可撤銷許可。'],['2. 你的內容與操作','你的檔案仍屬於你。刪除前請仔細檢查並備份重要資料。自動分類或建議可能不完整或不準確。'],['3. 權限與本機處理','部分功能需要你授予權限。你可在設定中撤銷，但相關功能可能無法使用。本機處理方式請參閱隱私權政策。'],['4. 購買與訂閱','購買由 Apple 處理。自動續訂會持續至你在下次續訂前取消。請透過 Apple Account 管理；解除安裝不會取消訂閱。'],['5. 退款','App Store 付款與退款由 Apple 依其政策及適用法律管理。'],['6. 可接受使用與智慧財產','不得違法使用、干擾安全機制、侵犯他人權利或未經許可散布應用程式。軟體、設計及品牌權利屬於開發者。'],['7. 可用性、保證與責任','功能可能變更或停止。在法律允許範圍內，本應用程式按「現狀」提供。強制適用的消費者權利不受影響。'],['8. 變更與聯絡','本條款可能更新。問題請寄至 <a href="mailto:lzq666amn@gmail.com">lzq666amn@gmail.com</a>。']]},
      support:{eyebrow:'說明 · 支援',title:'App 支援',lede:'尋找常見問題解答，或回報由 Zane Liao 開發的應用程式問題。',notice:'聯絡支援時，請註明裝置或 App Store 收據上顯示的正確 App 名稱。',sections:[['常見問題','<strong>如何恢復購買？</strong><br>使用購買時的 Apple Account 登入，並在 App 內使用「恢復購買」。<br><br><strong>無法存取照片或檔案？</strong><br>請在 iOS 設定中檢查權限。<br><br><strong>如何取消訂閱？</strong><br>開啟「設定」，點選姓名，再選擇「訂閱」及對應 App。'],['如何回報問題','寄信至 <a href="mailto:lzq666amn@gmail.com">lzq666amn@gmail.com</a>，註明 App 名稱、裝置、iOS 版本、重現步驟，以及不含敏感資訊的截圖。請勿傳送密碼或付款資料。'],['隱私權政策','請閱讀<a href="../privacy/">隱私權政策</a>。'],['訂閱與退款','訂閱由 Apple 計費及管理。解除安裝不會取消訂閱。App Store 退款要求由 Apple 依其政策審核。'],['回覆時間','我們會在合理可行範圍內儘快查看。複雜問題可能需要更多資訊或應用程式更新。']]}
    }
  };

  const lang=normalize(localStorage.getItem('language')||'en');
  const pageName=document.body.dataset.legalPage;
  const c=common[lang],page=(pages[lang]||pages.en)[pageName];
  document.documentElement.lang=lang;
  document.querySelectorAll('[data-language-select]').forEach(x=>x.value=lang);
  document.querySelectorAll('[data-common]').forEach(x=>x.textContent=c[x.dataset.common]);
  const set=(q,v)=>{const n=document.querySelector(q);if(n)n.innerHTML=v||'';};
  set('[data-page-eyebrow]',page.eyebrow);set('[data-page-title]',page.title);set('[data-page-lede]',page.lede);set('[data-page-updated]',pageName==='support'?'':c.updated);set('[data-page-notice]',page.notice);
  set('[data-app-label]',c.app);set('[data-app-value]',c.appValue);set('[data-email-label]',c.email);
  set('[data-page-content]',page.sections.map(([h,p])=>`<section><h2>${h}</h2><p>${p}</p></section>`).join(''));
  document.title=`${page.title} — Zane Liao`;
  document.addEventListener('change',e=>{if(!e.target.matches('[data-language-select]'))return;localStorage.setItem('language',normalize(e.target.value));location.reload();});
  document.querySelector('[data-theme-toggle]')?.addEventListener('click',()=>{const n=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=n;localStorage.setItem('theme',n);});
})();
